//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PgiWebPortalDBEntities : DbContext
    {
        public PgiWebPortalDBEntities()
            : base("name=PgiWebPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PGI_CandidateInfo> PGI_CandidateInfo { get; set; }
        public virtual DbSet<PGI_Candidate_EducationDetails> PGI_Candidate_EducationDetails { get; set; }
        public virtual DbSet<PGI_Candidate_EmploymentDetails> PGI_Candidate_EmploymentDetails { get; set; }
        public virtual DbSet<PGI_Candidate_PersonalDetails> PGI_Candidate_PersonalDetails { get; set; }
        public virtual DbSet<PGI_JobDetails> PGI_JobDetails { get; set; }
        public virtual DbSet<PGI_JobInfo> PGI_JobInfo { get; set; }
        public virtual DbSet<SKode_NumberSeries_T> SKode_NumberSeries_T { get; set; }
    }
}
