//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGI_Candidate_EducationDetails
    {
        public int ID { get; set; }
        public string UserCode { get; set; }
        public string EducationLevel { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> PassingYear { get; set; }
        public string Major { get; set; }
        public Nullable<int> Duration { get; set; }
        public string InstituteName { get; set; }
        public string Achievement { get; set; }
    }
}
