//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGI_Candidate_EmploymentDetails
    {
        public int ID { get; set; }
        public string UserCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string CompanyLocation { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Responsibilities { get; set; }
        public Nullable<System.DateTime> EmployeeFrom { get; set; }
        public Nullable<System.DateTime> EmployeeEnd { get; set; }
    }
}
