//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGI_ApplicationInfo
    {
        public int ID { get; set; }
        public string JobCode { get; set; }
        public string ApplicantCode { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Resume { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string CoverLetter { get; set; }
    }
}
