//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGI_CandidateInfo
    {
        public int ID { get; set; }
        public string UserCode { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNo { get; set; }
        public string UserPassword { get; set; }
        public string UserPhoto { get; set; }
        public string role { get; set; }
    }
}
