//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGI_JobDetails
    {
        public int ID { get; set; }
        public string JobCode { get; set; }
        public string JobDescription { get; set; }
        public string Responsibilities { get; set; }
        public string EducationalReq { get; set; }
        public string ExperienceReq { get; set; }
        public string AdditionalReq { get; set; }
        public string Benifits { get; set; }
    }
}
