//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGI_JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKode_NumberSeries_T
    {
        public int ID { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> SeriesLength { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> LastGeneratedNo { get; set; }
        public string CompanyID { get; set; }
        public string CatagoryIcon { get; set; }
    }
}
